on:
  push:
    branches:
      - master




jops:
  build:
    rins-on: ubuntu-latest

    steps:
      - name: 'test github action'
        run: pwd

      - name: 'test print'
        run: echo ahmed

